// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW_7v0HBK0SPRojztT-DESByCddIb4L0Y',
    appId: '1:931004742946:web:aff78709541c8af493397b',
    messagingSenderId: '931004742946',
    projectId: 'attendancesystem-9fd12',
    authDomain: 'attendancesystem-9fd12.firebaseapp.com',
    storageBucket: 'attendancesystem-9fd12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtL3sfHrKUk58vlkevfl5_PAeXbCC7b8A',
    appId: '1:931004742946:android:449118eac5280b3b93397b',
    messagingSenderId: '931004742946',
    projectId: 'attendancesystem-9fd12',
    storageBucket: 'attendancesystem-9fd12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_4h_f_6UDypI_t_7DDRD7565egx4WS10',
    appId: '1:931004742946:ios:33078deaf47cffc693397b',
    messagingSenderId: '931004742946',
    projectId: 'attendancesystem-9fd12',
    storageBucket: 'attendancesystem-9fd12.appspot.com',
    iosBundleId: 'com.example.ezitechtask',
  );
}
